#ifndef DEFINES_H
#define DEFINES_H

#define COORDINATE_DELIMITER ';'
#define ELEMENT_DELIMITER ','

#define TILE_SIZE 32
#define UNIT_WIDTH 40
#define UNIT_HEIGHT 64

#define PROJECTILE_SIZE 12

#define ENTITY_TYPE_BASE 0
#define ENTITY_TYPE_TILE 1
#define ENTITY_TYPE_DECORATIVE_TILE 2
#define ENTITY_TYPE_UNIT 3
#define ENTITY_TYPE_PROJECTILE 4

#define ENTITY_SUBTYPE_BASE_AIR 0
#define ENTITY_SUBTYPE_PLATFORM 1

#define ENTITY_SUBTYPE_PLAYER 0
#define ENTITY_SUBTYPE_NPC 1

enum Direction {DIRECTION_LEFT,
	DIRECTION_UPLEFT,
	DIRECTION_UP,
	DIRECTION_UPRIGHT,
	DIRECTION_RIGHT,
	DIRECTION_DOWNRIGHT,
	DIRECTION_DOWN,
	DIRECTION_DOWNLEFT,
	DIRECTION_NONE
};

#endif
